[passwords]
lucas = "lucasvozao"
jefferson = "JEFODE2025"
rallyson = "alienromulus"
leonardo = "plock392"
william = "848901"
michelle = "datamafia123"

[roles]
lucas = "admin"
jefferson = "user"
rallyson = "user"
leonardo = "user"
william = "user"
michelle = "user"