[passwords]
lucas = "lucasvozao"
jefferson = "JEFODE2025"
rallyson = "alienromulus"
leonardo = "plock392"
william = "848901"
michelle = "datamafia123"

[roles]
lucas = "admin"
jefferson = "user"
rallyson = "user"
leonardo = "user"
william = "user"
michelle = "user"

[mongo]
uri = "mongodb+srv://WilliamSoares21:SyOAtw7S3QVdTjBA@cluster-data-quality.aj5k3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-data-quality&ssl=true"