[passwords]
lucas = "senha_do_lucas"
jefferson = "senha_do_jefferson"
rallyson = "senha_do_rallyson"
leonardo = "senha_do_leonardo"
william = "senha_do_william"
michelle = "senha_do_michelle"

[roles]
lucas = "admin"
jefferson = "user"
rallyson = "user"
leonardo = "user"
william = "user"
michelle = "user"